### PR TITLE
fix bug in sweets with no eggs cli

### LINKED ISSUE #78: fix bug sweet with no eggs cli logic

### PR DESCRIPTION
**Pull request by MustafaIbrahim96**

### CODE REVIEW

File: src/main/kotlin/presentation/SweetsWithNoEggsCLi.kt [hunk 1]
```diff
@@ -8,51 +8,54 @@ class SweetsWithNoEggsCLi(private val sweetsWithNoEggsUseCase: SweetsWithNoEggsU
...
-        return try {
-            val meal = sweetsWithNoEggsUseCase.getRandomSweetsNoEggs()
-            println("|| Name: ${meal.name} || Description: ${meal.description}")
-            meal
-        } catch (exception: Exception) {
-            println("Error: ${exception.message}")
-            throw exception
-        }
-    }
+        menuLoop@ while (true) {
```
Comment (mostafa-n3ma) [inline src/main/kotlin/presentation/SweetsWithNoEggsCLi.kt]: nice loop naming you got here really cool idea to turn around the issue

File: src/main/kotlin/presentation/SweetsWithNoEggsCLi.kt [hunk 2]
```diff
@@ -8,51 +8,54 @@ class SweetsWithNoEggsCLi(private val sweetsWithNoEggsUseCase: SweetsWithNoEggsU
...
                 else -> println("Invalid input. Please enter 1 = Like , 2 = Dislike, or 3 = Exit.")
             }
         }
     }
 
-    private fun displayLikedDessertDetails(dessert: Recipe) {
-        println("Thank you for your choice!")
-        dessert.displayDetails()
+    private fun getRandomEggFreeDessert(): Recipe? {
+        return try {
```
Comment (mostafa-n3ma) [inline src/main/kotlin/presentation/SweetsWithNoEggsCLi.kt:53]: check the input handling utilities  i just pushed with the last PR about keto consider using them here to handle exceptions properly

**Review by mostafa-n3ma — CHANGES_REQUESTED** [review]

**Review by mostafa-n3ma — APPROVED** [review]
greate job , thank you for the quick  respond
